// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FnddsData.FnddsLoader.Entities;
using Microsoft.EntityFrameworkCore;

namespace FnddsData.FnddsLoader.Contexts;

public partial class FnddsDbContext : DbContext
{
    public FnddsDbContext(DbContextOptions<FnddsDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AddFoodDescription> AddFoodDescriptions { get; set; }

    public virtual DbSet<DerivDescription> DerivDescriptions { get; set; }

    public virtual DbSet<FnddsIngredient> FnddsIngredients { get; set; }

    public virtual DbSet<FnddsNutrientValue> FnddsNutrientValues { get; set; }

    public virtual DbSet<FnddsVersion> FnddsVersions { get; set; }

    public virtual DbSet<FoodPortionDescription> FoodPortionDescriptions { get; set; }

    public virtual DbSet<FoodWeight> FoodWeights { get; set; }

    public virtual DbSet<IngredNutrientValue> IngredNutrientValues { get; set; }

    public virtual DbSet<MainFoodDescription> MainFoodDescriptions { get; set; }

    public virtual DbSet<MoistureFatAdjustment> MoistureFatAdjustments { get; set; }

    public virtual DbSet<NutrientDescription> NutrientDescriptions { get; set; }

    public virtual DbSet<SubcodeDescription> SubcodeDescriptions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AddFoodDescription>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.SeqNum, e.VersionId });

            entity.ToTable("AddFoodDesc");

            entity.HasIndex(e => e.AdditionalFoodDescription, "IX_AddFoodDesc_AdditionalFoodDescription");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.AdditionalFoodDescription)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDescription).WithMany(p => p.AddFoodDescriptions)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_AddFoodDesc_MainFoodDesc");
        });

        modelBuilder.Entity<DerivDescription>(entity =>
        {
            entity.HasKey(e => new { e.DerivationCode, e.VersionId });

            entity.ToTable("DerivDesc");

            entity.Property(e => e.DerivationCode)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.DerivationDescription)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);

            entity.HasOne(d => d.Version).WithMany(p => p.DerivDescriptions)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_DerivDesc_FnddsVersion");
        });

        modelBuilder.Entity<FnddsIngredient>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.SeqNum, e.IngredientCode, e.VersionId });

            entity.ToTable("FnddsIngred");

            entity.HasIndex(e => e.IngredientCode, "IX_FnddsIngred_IngredientCode");

            entity.HasIndex(e => e.IngredientWeight, "IX_FnddsIngred_IngredientWeight");

            entity.HasIndex(e => e.PortionCode, "IX_FnddsIngred_PortionCode");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.Amount).HasColumnType("decimal(11, 3)");
            entity.Property(e => e.ChangeTypeToRetnCode)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ChangeTypeToSRCode)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ChangeTypeToWeight)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.IngredientDescription)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IngredientWeight).HasColumnType("decimal(11, 3)");
            entity.Property(e => e.Measure)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDescription).WithMany(p => p.FnddsIngredients)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_FnddsIngred_MainFoodDesc");

            entity.HasOne(d => d.FoodPortionDescription).WithMany(p => p.FnddsIngredients)
                .HasForeignKey(d => new { d.PortionCode, d.VersionId })
                .HasConstraintName("FK_FnddsIngred_FoodPortionDesc");
        });

        modelBuilder.Entity<FnddsNutrientValue>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.NutrientCode, e.VersionId });

            entity.ToTable("FnddsNutVal");

            entity.HasIndex(e => e.NutrientValue, "IX_FnddsNutVal_NutrientValue");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.NutrientValue).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDescription).WithMany(p => p.FnddsNutrientValues)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_FnddsNutVal_MainFoodDesc");

            entity.HasOne(d => d.NutrientDescription).WithMany(p => p.FnddsNutrientValues)
                .HasForeignKey(d => new { d.NutrientCode, d.VersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FnddsNutVal_NutDesc");
        });

        modelBuilder.Entity<FnddsVersion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FnddsVer__3214EC27E349BB29");

            entity.ToTable("FnddsVersion");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
        });

        modelBuilder.Entity<FoodPortionDescription>(entity =>
        {
            entity.HasKey(e => new { e.PortionCode, e.VersionId });

            entity.ToTable("FoodPortionDesc");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.ChangeType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.PortionDescription)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.Version).WithMany(p => p.FoodPortionDescriptions)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_FoodPortionDesc_FnddsVersion");
        });

        modelBuilder.Entity<FoodWeight>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.Subcode, e.SeqNum, e.PortionCode, e.VersionId });

            entity.ToTable("FoodWeight");

            entity.HasIndex(e => e.PortionWeight, "IX_FoodWeight_PortionWeight");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.ChangeType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.PortionWeight).HasColumnType("decimal(8, 3)");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDescription).WithMany(p => p.FoodWeights)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_FoodWeight_MainFoodDesc");

            entity.HasOne(d => d.FoodPortionDescription).WithMany(p => p.FoodWeights)
                .HasForeignKey(d => new { d.PortionCode, d.VersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodWeight_FoodPortionDesc");
        });

        modelBuilder.Entity<IngredNutrientValue>(entity =>
        {
            entity.HasKey(e => new { e.IngredientCode, e.NutrientCode, e.VersionId });

            entity.ToTable("IngredNutVal");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.DerivationCode)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.FdcId).HasColumnName("FdcID");
            entity.Property(e => e.IngredientDescription)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.NutrientValue).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.NutrientValueSource)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.NutrientDescription).WithMany(p => p.IngredNutrientValues)
                .HasForeignKey(d => new { d.NutrientCode, d.VersionId })
                .HasConstraintName("FK_IngredNutVal_NutDesc");
        });

        modelBuilder.Entity<MainFoodDescription>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.VersionId });

            entity.ToTable("MainFoodDesc");

            entity.HasIndex(e => e.MainFoodDescription1, "IX_MainFoodDesc_MainFoodDescription");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.AbbreviatedMainFoodDescription)
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.CategoryDescription)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.FortificationIdentifier)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.MainFoodDescription1)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("MainFoodDescription");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.Version).WithMany(p => p.MainFoodDescriptions)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_MainFoodDesc_FnddsVersion");
        });

        modelBuilder.Entity<MoistureFatAdjustment>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.VersionId });

            entity.ToTable("MoistNFatAdjust");

            entity.HasIndex(e => e.FoodCode, "IX_MoistNFatAdjust_FoodCode");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.FatChange).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.MoistureChange).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDescription).WithOne(p => p.MoistureFatAdjustment)
                .HasForeignKey<MoistureFatAdjustment>(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_MoistNFatAdjust_MainFoodDesc");
        });

        modelBuilder.Entity<NutrientDescription>(entity =>
        {
            entity.HasKey(e => new { e.NutrientCode, e.VersionId });

            entity.ToTable("NutDesc");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.NutrientDescription1)
                .IsRequired()
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasColumnName("NutrientDescription");
            entity.Property(e => e.Tagname)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Unit)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Version).WithMany(p => p.NutrientDescriptions)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_NutDesc_FnddsVersion");
        });

        modelBuilder.Entity<SubcodeDescription>(entity =>
        {
            entity.HasKey(e => new { e.Subcode, e.VersionId });

            entity.ToTable("SubcodeDesc");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");
            entity.Property(e => e.SubcodeDescription1)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("SubcodeDescription");

            entity.HasOne(d => d.Version).WithMany(p => p.SubcodeDescriptions)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_SubcodeDesc_FnddsVersion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}