// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FnddsData.FnddsLoader.Entities;
using Microsoft.EntityFrameworkCore;

namespace FnddsData.FnddsLoader.Contexts;

public partial class FnddsDbContext : DbContext
{
    public FnddsDbContext(DbContextOptions<FnddsDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AddFoodDesc> AddFoodDescs { get; set; }

    public virtual DbSet<DerivDesc> DerivDescs { get; set; }

    public virtual DbSet<FnddsIngred> FnddsIngreds { get; set; }

    public virtual DbSet<FnddsNutVal> FnddsNutVals { get; set; }

    public virtual DbSet<FnddsVersion> FnddsVersions { get; set; }

    public virtual DbSet<FoodPortionDesc> FoodPortionDescs { get; set; }

    public virtual DbSet<FoodWeight> FoodWeights { get; set; }

    public virtual DbSet<IngredNutVal> IngredNutVals { get; set; }

    public virtual DbSet<MainFoodDesc> MainFoodDescs { get; set; }

    public virtual DbSet<MoistNFatAdjust> MoistNFatAdjusts { get; set; }

    public virtual DbSet<NutDesc> NutDescs { get; set; }

    public virtual DbSet<SubcodeDesc> SubcodeDescs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AddFoodDesc>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.SeqNum, e.VersionId });

            entity.ToTable("AddFoodDesc");

            entity.HasIndex(e => e.AdditionalFoodDescription, "IX_AddFoodDesc_AdditionalFoodDescription");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.AdditionalFoodDescription)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDesc).WithMany(p => p.AddFoodDescs)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_AddFoodDesc_MainFoodDesc");
        });

        modelBuilder.Entity<DerivDesc>(entity =>
        {
            entity.HasKey(e => new { e.DerivationCode, e.VersionId });

            entity.ToTable("DerivDesc");

            entity.Property(e => e.DerivationCode)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.DerivationDescription)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);

            entity.HasOne(d => d.Version).WithMany(p => p.DerivDescs)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_DerivDesc_FnddsVersion");
        });

        modelBuilder.Entity<FnddsIngred>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.SeqNum, e.IngredientCode, e.VersionId });

            entity.ToTable("FnddsIngred");

            entity.HasIndex(e => e.IngredientCode, "IX_FnddsIngred_IngredientCode");

            entity.HasIndex(e => e.IngredientWeight, "IX_FnddsIngred_IngredientWeight");

            entity.HasIndex(e => e.PortionCode, "IX_FnddsIngred_PortionCode");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.Amount).HasColumnType("decimal(11, 3)");
            entity.Property(e => e.ChangeTypeToRetnCode)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ChangeTypeToSRCode)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ChangeTypeToWeight)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.IngredientDescription)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.IngredientWeight).HasColumnType("decimal(11, 3)");
            entity.Property(e => e.Measure)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDesc).WithMany(p => p.FnddsIngreds)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_FnddsIngred_MainFoodDesc");

            entity.HasOne(d => d.FoodPortionDesc).WithMany(p => p.FnddsIngreds)
                .HasForeignKey(d => new { d.PortionCode, d.VersionId })
                .HasConstraintName("FK_FnddsIngred_FoodPortionDesc");
        });

        modelBuilder.Entity<FnddsNutVal>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.NutrientCode, e.VersionId });

            entity.ToTable("FnddsNutVal");

            entity.HasIndex(e => e.NutrientValue, "IX_FnddsNutVal_NutrientValue");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.NutrientValue).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDesc).WithMany(p => p.FnddsNutVals)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_FnddsNutVal_MainFoodDesc");

            entity.HasOne(d => d.NutDesc).WithMany(p => p.FnddsNutVals)
                .HasForeignKey(d => new { d.NutrientCode, d.VersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FnddsNutVal_NutDesc");
        });

        modelBuilder.Entity<FnddsVersion>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FnddsVer__3214EC27E349BB29");

            entity.ToTable("FnddsVersion");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
        });

        modelBuilder.Entity<FoodPortionDesc>(entity =>
        {
            entity.HasKey(e => new { e.PortionCode, e.VersionId });

            entity.ToTable("FoodPortionDesc");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.ChangeType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.PortionDescription)
                .IsRequired()
                .HasMaxLength(120)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.Version).WithMany(p => p.FoodPortionDescs)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_FoodPortionDesc_FnddsVersion");
        });

        modelBuilder.Entity<FoodWeight>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.Subcode, e.SeqNum, e.PortionCode, e.VersionId });

            entity.ToTable("FoodWeight");

            entity.HasIndex(e => e.PortionWeight, "IX_FoodWeight_PortionWeight");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.ChangeType)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.PortionWeight).HasColumnType("decimal(8, 3)");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDesc).WithMany(p => p.FoodWeights)
                .HasForeignKey(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_FoodWeight_MainFoodDesc");

            entity.HasOne(d => d.FoodPortionDesc).WithMany(p => p.FoodWeights)
                .HasForeignKey(d => new { d.PortionCode, d.VersionId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FoodWeight_FoodPortionDesc");
        });

        modelBuilder.Entity<IngredNutVal>(entity =>
        {
            entity.HasKey(e => new { e.IngredientCode, e.NutrientCode, e.VersionId });

            entity.ToTable("IngredNutVal");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.DerivationCode)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.FdcId).HasColumnName("FdcID");
            entity.Property(e => e.IngredientDescription)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.NutrientValue).HasColumnType("decimal(10, 3)");
            entity.Property(e => e.NutrientValueSource)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.NutDesc).WithMany(p => p.IngredNutVals)
                .HasForeignKey(d => new { d.NutrientCode, d.VersionId })
                .HasConstraintName("FK_IngredNutVal_NutDesc");
        });

        modelBuilder.Entity<MainFoodDesc>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.VersionId });

            entity.ToTable("MainFoodDesc");

            entity.HasIndex(e => e.MainFoodDescription, "IX_MainFoodDesc_MainFoodDescription");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.AbbreviatedMainFoodDescription)
                .HasMaxLength(60)
                .IsUnicode(false);
            entity.Property(e => e.CategoryDescription)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.FortificationIdentifier)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.MainFoodDescription)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.Version).WithMany(p => p.MainFoodDescs)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_MainFoodDesc_FnddsVersion");
        });

        modelBuilder.Entity<MoistNFatAdjust>(entity =>
        {
            entity.HasKey(e => new { e.FoodCode, e.VersionId });

            entity.ToTable("MoistNFatAdjust");

            entity.HasIndex(e => e.FoodCode, "IX_MoistNFatAdjust_FoodCode");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.FatChange).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.MoistureChange).HasColumnType("decimal(5, 1)");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");

            entity.HasOne(d => d.MainFoodDesc).WithOne(p => p.MoistNFatAdjust)
                .HasForeignKey<MoistNFatAdjust>(d => new { d.FoodCode, d.VersionId })
                .HasConstraintName("FK_MoistNFatAdjust_MainFoodDesc");
        });

        modelBuilder.Entity<NutDesc>(entity =>
        {
            entity.HasKey(e => new { e.NutrientCode, e.VersionId });

            entity.ToTable("NutDesc");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.NutrientDescription)
                .IsRequired()
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.Tagname)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.Unit)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.Version).WithMany(p => p.NutDescs)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_NutDesc_FnddsVersion");
        });

        modelBuilder.Entity<SubcodeDesc>(entity =>
        {
            entity.HasKey(e => new { e.Subcode, e.VersionId });

            entity.ToTable("SubcodeDesc");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateDt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("CreateDT");
            entity.Property(e => e.EndDt).HasColumnName("EndDT");
            entity.Property(e => e.StartDt).HasColumnName("StartDT");
            entity.Property(e => e.SubcodeDescription)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);

            entity.HasOne(d => d.Version).WithMany(p => p.SubcodeDescs)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_SubcodeDesc_FnddsVersion");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}