// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodAndNutrientData.FnddsImporter.Entities;

public partial class FnddsIngredEquiv
{
    public int FoodCode { get; set; }

    public int SeqNum { get; set; }

    public int IngredientCode { get; set; }

    public int VersionId { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual FnddsIngred FnddsIngred { get; set; }

    public virtual IngredEquiv IngredEquiv { get; set; }
}