// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodAndNutrientData.FnddsImporter.Entities;

public partial class IngredEquiv
{
    public int IngredientCode { get; set; }

    public int VersionId { get; set; }

    public string IngredientDescription { get; set; }

    public decimal? F_TOTAL { get; set; }

    public decimal? F_CITMLB { get; set; }

    public decimal? F_OTHER { get; set; }

    public decimal? F_JUICE { get; set; }

    public decimal? V_TOTAL { get; set; }

    public decimal? V_DRKGR { get; set; }

    public decimal? V_REDOR_TOTAL { get; set; }

    public decimal? V_REDOR_TOMATO { get; set; }

    public decimal? V_REDOR_OTHER { get; set; }

    public decimal? V_STARCHY_TOTAL { get; set; }

    public decimal? V_STARCHY_POTATO { get; set; }

    public decimal? V_STARCHY_OTHER { get; set; }

    public decimal? V_OTHER { get; set; }

    public decimal? V_LEGUMES { get; set; }

    public decimal? G_TOTAL { get; set; }

    public decimal? G_WHOLE { get; set; }

    public decimal? G_REFINED { get; set; }

    public decimal? PF_TOTAL { get; set; }

    public decimal? PF_MPS_TOTAL { get; set; }

    public decimal? PF_MEAT { get; set; }

    public decimal? PF_CUREDMEAT { get; set; }

    public decimal? PF_ORGAN { get; set; }

    public decimal? PF_POULT { get; set; }

    public decimal? PF_SEAFD_HI { get; set; }

    public decimal? PF_SEAFD_LOW { get; set; }

    public decimal? PF_EGGS { get; set; }

    public decimal? PF_SOY { get; set; }

    public decimal? PF_NUTSDS { get; set; }

    public decimal? PF_LEGUMES { get; set; }

    public decimal? D_TOTAL { get; set; }

    public decimal? D_MILK { get; set; }

    public decimal? D_YOGURT { get; set; }

    public decimal? D_CHEESE { get; set; }

    public decimal? OILS { get; set; }

    public decimal? SOLID_FATS { get; set; }

    public decimal? ADD_SUGARS { get; set; }

    public decimal? A_DRINKS { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<FnddsIngredEquiv> FnddsIngredEquivs { get; set; } = new List<FnddsIngredEquiv>();
}