// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodAndNutrientData.FnddsImporter.Entities;

public partial class ModDesc
{
    public int? FoodCode { get; set; }

    public int ModificationCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string ModificationDescription { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual MainFoodDesc MainFoodDesc { get; set; }

    public virtual ModEquiv ModEquiv { get; set; }

    public virtual ICollection<ModNutVal> ModNutVals { get; set; } = new List<ModNutVal>();
}