// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FoodAndNutrientData.FnddsImporter.Entities;

public partial class ModNutVal
{
    public int ModificationCode { get; set; }

    public int NutrientCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public decimal NutrientValue { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ModDesc ModDesc { get; set; }
}