// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class AddFoodDesc
{
    public int FoodCode { get; set; }

    public int SeqNum { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string AdditionalFoodDescription { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual MainFoodDesc MainFoodDesc { get; set; }
}