// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class DerivDesc
{
    public string DerivationCode { get; set; }

    public int VersionId { get; set; }

    public string DerivationDescription { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual FnddsVersion Version { get; set; }
}