// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class FnddsVersion
{
    public int Id { get; set; }

    public int BeginYear { get; set; }

    public int EndYear { get; set; }

    public int? Major { get; set; }

    public int? Minor { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<DerivDesc> DerivDescs { get; set; } = new List<DerivDesc>();

    public virtual ICollection<FoodPortionDesc> FoodPortionDescs { get; set; } = new List<FoodPortionDesc>();

    public virtual ICollection<MainFoodDesc> MainFoodDescs { get; set; } = new List<MainFoodDesc>();

    public virtual ICollection<NutDesc> NutDescs { get; set; } = new List<NutDesc>();

    public virtual ICollection<SubcodeDesc> SubcodeDescs { get; set; } = new List<SubcodeDesc>();
}