// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class FnddsNutVal
{
    public int FoodCode { get; set; }

    public int NutrientCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public decimal NutrientValue { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual MainFoodDesc MainFoodDesc { get; set; }

    public virtual NutDesc NutDesc { get; set; }
}