// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class FnddsVersion
{
    public int Id { get; set; }

    public int BeginYear { get; set; }

    public int EndYear { get; set; }

    public int? Major { get; set; }

    public int? Minor { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<DerivDescription> DerivDescriptions { get; set; } = new List<DerivDescription>();

    public virtual ICollection<FoodPortionDescription> FoodPortionDescriptions { get; set; } = new List<FoodPortionDescription>();

    public virtual ICollection<MainFoodDescription> MainFoodDescriptions { get; set; } = new List<MainFoodDescription>();

    public virtual ICollection<NutrientDescription> NutrientDescriptions { get; set; } = new List<NutrientDescription>();

    public virtual ICollection<SubcodeDescription> SubcodeDescriptions { get; set; } = new List<SubcodeDescription>();
}