// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class FnddsIngred
{
    public int FoodCode { get; set; }

    public int SeqNum { get; set; }

    public int IngredientCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string IngredientDescription { get; set; }

    public decimal Amount { get; set; }

    public string Measure { get; set; }

    public int? PortionCode { get; set; }

    public int? RetentionCode { get; set; }

    public int? Flag { get; set; }

    public decimal IngredientWeight { get; set; }

    public string ChangeTypeToSRCode { get; set; }

    public string ChangeTypeToWeight { get; set; }

    public string ChangeTypeToRetnCode { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual FoodPortionDesc FoodPortionDesc { get; set; }

    public virtual MainFoodDesc MainFoodDesc { get; set; }
}