// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class FoodWeight
{
    public int FoodCode { get; set; }

    public int Subcode { get; set; }

    public int SeqNum { get; set; }

    public int PortionCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public decimal PortionWeight { get; set; }

    public string ChangeType { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual FoodPortionDesc FoodPortionDesc { get; set; }

    public virtual MainFoodDesc MainFoodDesc { get; set; }
}