// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class FoodPortionDescription
{
    public int PortionCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string PortionDescription { get; set; }

    public string ChangeType { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<FnddsIngredient> FnddsIngredients { get; set; } = new List<FnddsIngredient>();

    public virtual ICollection<FoodWeight> FoodWeights { get; set; } = new List<FoodWeight>();

    public virtual FnddsVersion Version { get; set; }
}