// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class IngredNutVal
{
    public int IngredientCode { get; set; }

    public int NutrientCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string IngredientDescription { get; set; }

    public decimal NutrientValue { get; set; }

    public string NutrientValueSource { get; set; }

    public int? FdcId { get; set; }

    public string DerivationCode { get; set; }

    public int? SRAddModYear { get; set; }

    public int? FoundationYearAcquired { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual NutDesc NutDesc { get; set; }
}