// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class MainFoodDescription
{
    public int FoodCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string MainFoodDescription1 { get; set; }

    public string AbbreviatedMainFoodDescription { get; set; }

    public string FortificationIdentifier { get; set; }

    public int? CategoryNumber { get; set; }

    public string CategoryDescription { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<AddFoodDescription> AddFoodDescriptions { get; set; } = new List<AddFoodDescription>();

    public virtual ICollection<FnddsIngredient> FnddsIngredients { get; set; } = new List<FnddsIngredient>();

    public virtual ICollection<FnddsNutrientValue> FnddsNutrientValues { get; set; } = new List<FnddsNutrientValue>();

    public virtual ICollection<FoodWeight> FoodWeights { get; set; } = new List<FoodWeight>();

    public virtual MoistureFatAdjustment MoistureFatAdjustment { get; set; }

    public virtual FnddsVersion Version { get; set; }
}