// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class MainFoodDesc
{
    public int FoodCode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string MainFoodDescription { get; set; }

    public string AbbreviatedMainFoodDescription { get; set; }

    public string FortificationIdentifier { get; set; }

    public int? CategoryNumber { get; set; }

    public string CategoryDescription { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<AddFoodDesc> AddFoodDescs { get; set; } = new List<AddFoodDesc>();

    public virtual ICollection<FnddsIngred> FnddsIngreds { get; set; } = new List<FnddsIngred>();

    public virtual ICollection<FnddsNutVal> FnddsNutVals { get; set; } = new List<FnddsNutVal>();

    public virtual ICollection<FoodWeight> FoodWeights { get; set; } = new List<FoodWeight>();

    public virtual MoistNFatAdjust MoistNFatAdjust { get; set; }

    public virtual FnddsVersion Version { get; set; }
}