// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class NutDesc
{
    public int NutrientCode { get; set; }

    public int VersionId { get; set; }

    public string NutrientDescription { get; set; }

    public string Tagname { get; set; }

    public string Unit { get; set; }

    public int Decimals { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<FnddsNutVal> FnddsNutVals { get; set; } = new List<FnddsNutVal>();

    public virtual ICollection<IngredNutVal> IngredNutVals { get; set; } = new List<IngredNutVal>();

    public virtual FnddsVersion Version { get; set; }
}