// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class NutrientDescription
{
    public int NutrientCode { get; set; }

    public int VersionId { get; set; }

    public string NutrientDescription1 { get; set; }

    public string Tagname { get; set; }

    public string Unit { get; set; }

    public int Decimals { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual ICollection<FnddsNutrientValue> FnddsNutrientValues { get; set; } = new List<FnddsNutrientValue>();

    public virtual ICollection<IngredNutrientValue> IngredNutrientValues { get; set; } = new List<IngredNutrientValue>();

    public virtual FnddsVersion Version { get; set; }
}