// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FnddsData.FnddsLoader.Entities;

public partial class SubcodeDesc
{
    public int Subcode { get; set; }

    public int VersionId { get; set; }

    public DateTime? StartDt { get; set; }

    public DateTime? EndDt { get; set; }

    public string SubcodeDescription { get; set; }

    public DateTime CreateDt { get; set; }

    public virtual FnddsVersion Version { get; set; }
}